- name: This is a playbook test
  hosts: all
  gather_facts: false


  tasks:
  - name: Run bhost on LSF nodes to find NJOBS count
    ansible.builtin.shell:
      cmd: "bhosts -o \"HOST_NAME NJOBS\" -json"
    register: lsf_output

  - ansible.builtin.set_fact:
      clean_lsf_output: "{{ lsf_output.stdout | replace('\','')  }}"
  
  - ansible.builtin.debug:
      msg: "{{ clean_lsf_output.RECORDS[0] }}"
  
  - name: Select hosts with NJOBS = 0
    ansible.builtin.debug: 
      msg: "The host {{ clean_lsf_output.RECORDS[item].HOST_NAME }} has {{ clean_lsf_output.RECORDS[item].NJOBS }} jobs."
        
    
