- name: This is a playbook test
  hosts: all
  gather_facts: false


  tasks:
  - name: This is a test 
    ansible.builtin.shell:
      cmd: "bhosts -o \"HOST_NAME NJOBS\" -json"
    register: lsf_output

  - ansible.builtin.debug:
      msg: "{{ lsf_output.stdout_lines }}"
  
  # - name: Pick up lines we are interested in
  #   ansible.utils.cli_parse:
  #     command: "bhosts -o \"HOST_NAME NJOBS\" -json"
  #     parser:
  #       name: ansible.utils.json
  #   register: lsf_output
        
    
