- name: This is a playbook test
  hosts: all
  gather_facts: false


  tasks:
  - name: Run bhost on LSF nodes to find NJOBS count
    ansible.builtin.shell:
      cmd: "bhosts -o \"HOST_NAME NJOBS\" -json"
    register: lsf_output

  - ansible.builtin.set_fact:
      clean_lsf_output: "{{ lsf_output.stdout | replace('\','')  }}"
  
  - ansible.builtin.debug:
      msg: "{{ clean_lsf_output.RECORDS[0].HOST_NAME }}"
  
  - name: Set facts
    ansible.builtin.set_fact:
      hostnames: "{{ item.RECORDS.HOST_NAME }}"
      njobs: "{{ item.RECORDS.NJOBS }}"
    with_items: "{{ clean_lsf_output }}"

  

        
    
