- name: List LSF nodes bhost jobs 
  hosts: all
  connection: local

  tasks: 
- name: Run command "hostname" on rhel and register
  ansible.builtin.command: 
    cmd: bhosts -o "HOST_NAME NJOBS"
  register: lsf_output
  
  ansible.builtin.debug:
    var: lsf_output

