- name: This is a playbook test
  hosts: all
  connection: local 
  become: true
  gather_facts: true 


  tasks:
  - name: This is a test 
    ansible.builtin.command:
      cmd: "cat /etc/redhat-release" 
    register: lsf_output

  - ansible.builtin.debug:
      var: lsf_output
