- name: This is a playbook test
  hosts: all
  gather_facts: false


  tasks:
  - name: Run bhost on LSF nodes to find NJOBS count
    ansible.builtin.shell:
      cmd: "bhosts -o \"HOST_NAME NJOBS\" -json"
    register: lsf_output
    run_once: true

  - ansible.builtin.set_fact:
      clean_lsf_output: "{{ lsf_output.stdout | replace('\','') }}"
  
  - name: set njobs by host
    vars:
      njobs_all: "{{ clean_lsf_output.RECORDS | items2dict(key_name='HOST_NAME', value_name='NJOBS') }}"
    set_fact:
      njobs: "{{ njobs_all[inventory_hostname] }}"
      
  - name: If LSF node has 0 jobs, patch the server
    ansible.builtin.shell:
      cmd: "echo This is a TEST!"
    when: ansible_facts['njobs'] == 0

  

        
    
