- name: This is a playbook test
  hosts: all
  gather_facts: false


  tasks:
  - name: This is a test 
    ansible.builtin.shell:
      cmd: "bhosts -o \"HOST_NAME NJOBS\" -json"
    register: lsf_output

  - ansible.builtin.debug:
      msg: "{{ lsf_output.rc }}"

  # - name: Stop jobs if NJOBS = 0
  #   ansible.builtin.shell:
  #     cmd: "This is a test!"
  #     when: "\"NJOBs\\\" : 0,' in lsf_output.stdout"
