- name: This is a playbook test
  hosts: all
  gather_facts: false


  tasks:
  - name: This is a test 
    ansible.builtin.shell:
      cmd: "bhosts -o \"HOST_NAME NJOBS\""
    register: lsf_output

  - ansible.builtin.debug:
      msg: "{{ lsf_output }}"

  - name: Pick up lines we are interested in
    set_fact:
      important_lines: "{{ important_lines|default([]) + [item] }}"
    when: item.split(" ")
    with items:
    - "{{ lsf_output }}"
    
