- name: This is a playbook test
  hosts: all
  gather_facts: false


  tasks:
  - name: This is a test 
    ansible.builtin.shell:
      cmd: "bhosts -o \"HOST_NAME NJOBS\" -json"
      register: lsf_output

  - ansible.builtin.debug:
      var: lsf_output
