- name: This playbook with patch RHEL hosts when njobs == 0
  hosts: all
  gather_facts: false

  tasks:
  - ansible.builtin.debug:
      var: njobs
  
  - name: Patch LSF servers if njobs == 0
    ansible.builtin.yum:
      name: '*'
      state: latest
    become: yes
    when: njobs == "0"
